In [174]:
import numpy as np

In [175]:
field=np.zeros([3,4])

In [176]:
bombas=[[0,0],[0,1]]

In [177]:
A


[[0, 0], [0, 1]]

In [178]:
columnas=4
renglones=3

In [179]:
for bomba in bombas:
    print(bomba)
    
    renglon=bomba[0]
    columna=bomba[1]
    
    field[renglon][columna]=-1
    
    for i in range(renglon-1, renglon+2):
        for j in range(columna-1, columna+2):
            print(i, ',', j)
       
            if 0<=i<renglones and 0<=j<columnas and field[i][j]!=-1:
                field[i][j]+=1


[0, 0]
-1 , -1
-1 , 0
-1 , 1
0 , -1
0 , 0
0 , 1
1 , -1
1 , 0
1 , 1
[0, 1]
-1 , 0
-1 , 1
-1 , 2
0 , 0
0 , 1
0 , 2
1 , 0
1 , 1
1 , 2


In [180]:
field

array([[-1., -1.,  1.,  0.],
       [ 2.,  2.,  1.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [181]:
def busca_minas(bombas,renglones,columnas):
    field=np.zeros([renglones,columnas])
    for bomba in bombas:    
        renglon=bomba[0]
        columna=bomba[1]
        field[renglon][columna]=-1
        for i in range(renglon-1, renglon+2):
            for j in range(columna-1, columna+2):
                if 0<=i<renglones and 0<=j<columnas and field[i][j]!=-1:
                    field[i][j]+=1
    return field
    
    

In [182]:
busca_minas(bombas,renglones,columnas)

array([[-1., -1.,  1.,  0.],
       [ 2.,  2.,  1.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [183]:
(field==0)
field.shape[0]



3

In [184]:
given_i=2
given_j=2

In [185]:
field

array([[-1., -1.,  1.,  0.],
       [ 2.,  2.,  1.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [186]:
import queue


In [187]:
def click(field,renglones,columnas, given_i,given_j):
    to_check=queue.Queue()
    if field[given_i][given_j]!=0:
        return field
    else:
        field[given_i][given_j]=-2
        to_check.put((given_i,given_j))
    
    while not to_check.empty():
        (current_i,current_j)=to_check.get()
        for i in range((current_i-1),(current_i+2)):
            for j in range((current_j-1),(current_j+2)):
                if 0<=i<renglones and 0<=j<columnas and field[i][j]==0:
                    field[i][j]=-2
                    to_check.put((i,j))
    return field
        
        
        

In [188]:
click(field,renglones,columnas,given_i,given_j)

array([[-1., -1.,  1., -2.],
       [ 2.,  2.,  1., -2.],
       [-2., -2., -2., -2.]])

In [189]:
bombas=[[0,0],[3,3]]
renglones=4
columnas=4

In [190]:
field=busca_minas(bombas,renglones,columnas)

In [191]:
field

array([[-1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.],
       [ 0.,  0.,  1., -1.]])

In [192]:
given_i=1
given_j=2


In [193]:
click(field,renglones,columnas,given_i,given_j)

array([[-1.,  1., -2., -2.],
       [ 1.,  1., -2., -2.],
       [-2., -2.,  1.,  1.],
       [-2., -2.,  1., -1.]])